# Oh My Posh Configuration
schema = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
final_space = true
version = 3

[[blocks]]
type = "prompt"
alignment = "left"
newline = true

# Primary Context
[[blocks.segments]]
type = "os"
style = "plain"
background = "transparent"
foreground = "#45eb45"     # VT100 P1 phosphor green (palette 2)
template = " {{ .Icon }} "

[[blocks.segments]]
type = "session"
style = "plain"
background = "transparent"
foreground = "#f2fff2"     # Bright white (palette 15)
template = "{{ if .SSHSession }}<#f7bf2b> \uf817 SSH</> {{ end }}{{ .UserName }} "  # Wyse 60 amber (palette 3)

[blocks.segments.properties]
display_host = false
ssh_symbol = "\uf817"      # Network/SSH icon from Nerd Fonts

[[blocks.segments]]
type = "shell"
style = "plain"
background = "transparent"
foreground = "#45eb45"     # VT100 green
template = " \uf489 {{ .Name }} "

[[blocks.segments]]
type = "path"
style = "plain"
background = "transparent"
foreground = "#4066f2"     # IBM 3278 blue (palette 4)
template = " {{ .Path }} "

[blocks.segments.properties]
style = "agnoster"
max_depth = 3
enable_hyperlink = true
prefix = ""
path_separator = " <#4c594c>\ue0b1</> "  # Darker green (palette 8) for subtle separation
home_icon = "\uf015"
folder_icon = "\uf115"
mapped_locations = [
  [
    "~",
    "\uf015",
  ],
  [
    ".git",
    "\uf1d3",
  ],
  [
    "node_modules",
    "\ue718",
  ],
  [
    ".config",
    "\ue615",
  ],
  [
    "Downloads",
    "\uf498",
  ],
]

[[blocks.segments]]
type = "git"
style = "plain"
background = "transparent"
foreground = "#45eb45"     # VT100 green (primary terminal color)
template = " {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }} <#f7bf2b>{{ .Working.String }}</>{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }} <#f7bf2b>{{ .Staging.String }}</>{{ end }}{{ if gt .StashCount 0 }} \uf692 {{ .StashCount }}{{ end }} "

[blocks.segments.properties]
branch_max_length = 25
fetch_stash_count = true
fetch_status = true
branch_icon = "\uf418 "
branch_identical_icon = "\uf444"
branch_gone_icon = "\ueab8"

# Changed from background templates to foreground for transparent style
foreground_templates = [
  "{{ if or (.Working.Changed) (.Staging.Changed) }}#f7bf2b{{ end }}",  # Wyse amber for changes
  "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#f2fff2{{ end }}",         # Bright white
  "{{ if gt .Ahead 0 }}#bf4cf2{{ end }}",                              # Purple (palette 5)
  "{{ if gt .Behind 0 }}#bf4cf2{{ end }}",                             # Purple (palette 5)
]

# Development Environment
[[blocks.segments]]
type = "python"
style = "plain"
background = "transparent"
foreground = "#ffd933"     # Bright amber (palette 11) - close to Python's yellow
template = " \ue235 {{ if .Error }}<#ff6666>{{ .Error }}</>{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ .Full }}{{ end }} "

[blocks.segments.properties]
display_mode = "files"
display_version = true
display_virtual_env = true
home_enabled = true

[[blocks.segments]]
type = "node"
style = "plain"
background = "transparent"
foreground = "#59ff59"     # Bright green (palette 10)
template = " \ue718 {{ if .Error }}<#ff6666>{{ .Error }}</>{{ else }}{{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }}{{ end }} "

[blocks.segments.properties]
fetch_package_manager = true
npm_icon = " <#ff6666>\ue5fa</> "   # Bright red (palette 9)
yarn_icon = " <#59e6ff>\ue6a7</>"   # Bright cyan (palette 14)

[[blocks.segments]]
type = "rust"
style = "plain"
background = "transparent"
foreground = "#f7bf2b"     # Wyse amber (palette 3)
template = " \ue7a8 {{ if .Error }}<#ff6666>{{ .Error }}</>{{ else }}{{ .Full }}{{ end }} "

[[blocks.segments]]
type = "go"
style = "plain"
background = "transparent"
foreground = "#40d9e6"     # Cyan (palette 6)
template = " \ue626 {{ if .Error }}<#ff6666>{{ .Error }}</>{{ else }}{{ .Full }}{{ end }} "

[[blocks.segments]]
type = "java"
style = "plain"
background = "transparent"
foreground = "#de5454"     # Commodore red (palette 1)
template = " \ue738 {{ if .Error }}<#ff6666>{{ .Error }}</>{{ else }}{{ .Full }}{{ end }} "

[[blocks.segments]]
type = "dotnet"
style = "plain"
background = "transparent"
foreground = "#4066f2"     # IBM blue (palette 4)
template = " \ue77f {{ if .Unsupported }}<#ff6666>\uf071</>{{ else }}{{ .Full }}{{ end }} "

[[blocks.segments]]
type = "dart"
style = "plain"
background = "transparent"
foreground = "#40d9e6"     # Cyan (palette 6)
template = " \ue798 {{ if .Error }}<#ff6666>{{ .Error }}</>{{ else }}{{ .Full }}{{ end }} "

[[blocks.segments]]
type = "angular"
style = "plain"
background = "transparent"
foreground = "#de5454"     # Commodore red (palette 1)
template = " \ue753 {{ if .Error }}<#ff6666>{{ .Error }}</>{{ else }}{{ .Full }}{{ end }} "

[[blocks.segments]]
type = "ruby"
style = "plain"
background = "transparent"
foreground = "#de5454"     # Commodore red (palette 1)
template = " \ue791 {{ if .Error }}<#ff6666>{{ .Error }}</>{{ else }}{{ .Full }}{{ end }} "

# System Status
[[blocks.segments]]
type = "sysinfo"
style = "plain"
background = "transparent"
foreground = "#4066f2"     # IBM blue for system resources
template = " \uf85a {{ round .PhysicalPercentUsed .Precision }}% "

[blocks.segments.properties]
physical_memory_only = true
precision = 1

[[blocks.segments]]
type = "battery"
style = "plain"
background = "transparent"
foreground = "#45eb45"     # VT100 green for power status
template = " {{ if not .Error }}{{ if eq .State.String \"Charging\" }}\uf583{{ else if eq .State.String \"Discharging\" }}\uf57e{{ else if eq .State.String \"Full\" }}\uf578{{ end }} {{ .Percentage }}%{{ end }} "

[blocks.segments.properties]
display_error = false
charging_icon = "\uf583"
discharging_icon = "\uf57e"
charged_icon = "\uf578"

[[blocks.segments]]
type = "executiontime"
style = "plain"
background = "transparent"
foreground = "#f2fff2"     # Bright white for clarity
template = " \ueba2 {{ if gt .Ms 1000 }}{{ round (div .Ms 1000) 1 }}s{{ else }}{{ .Ms }}ms{{ end }} "

[blocks.segments.properties]
style = "austin"
always_enabled = true
threshold = 100       # Only show if command takes more than 100ms

[[blocks.segments]]
type = "time"
style = "plain"
background = "transparent"
foreground = "#f7bf2b"     # Wyse amber for reference information
template = " \uf073 {{ .CurrentDate | date .Format }} "

[blocks.segments.properties]
time_format = "15:04:05"

# Second block for prompt character
[[blocks]]
type = "prompt"
alignment = "left"
newline = true

[[blocks.segments]]
type = "text"
style = "plain"
foreground_templates = [
  "{{if gt .Code 0}}#ff6666{{end}}",  # Bright red (palette 9) for errors
  "{{if eq .Code 0}}#45eb45{{end}}",  # VT100 green (palette 2) for success
]
template = "{{ if .Root }}#{{else}}${{end}}"

[transient_prompt]
template = "❯ "
background = "transparent"
foreground_templates = [
  "{{if gt .Code 0}}#ff6666{{end}}",  # Bright red (palette 9) for errors
  "{{if eq .Code 0}}#45eb45{{end}}",  # VT100 green (palette 2) for success
]

[secondary_prompt]
template = "❯❯ "
foreground = "#45eb45"  # VT100 green (palette 2)
background = "transparent"
