# Oh My Posh Configuration
#:schema = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
final_space = true
version = 3

[[blocks]]
type = "prompt"
alignment = "left"
newline = true

[[blocks.segments]]
type = "os"
style = "plain"
background = "transparent"
foreground = "#4AF626"  # Keeping our signature green
template = " {{ .Icon }} "

[blocks.segments.properties]
alpine = "\uf300"
arch = "\uf303"
centos = "\uf304"
debian = "\uf306"
elementary = "\uf309"
fedora = "\uf30a"
gentoo = "\uf30d"
linux = "\ue712"
macos = "\ue711"
manjaro = "\uf312"
mint = "\uf30f"
opensuse = "\uf314"
raspbian = "\uf315"
ubuntu = "\uf31c"
windows = "\ue70f"

[[blocks.segments]]
type = "session"
style = "plain"
background = "transparent"
foreground = "#D8DEE9"  # Soft white
template = " {{ .UserName }} "

[[blocks.segments]]
type = "path"
style = "plain"
background = "transparent"
foreground = "#3B7AC9"  # Refined IBM blue
template = " {{ .Path }} "

[blocks.segments.properties]
style = "agnoster"
max_depth = 3
enable_hyperlink = true
prefix = ""
path_separator = "/"
home_icon = "\uf015"
folder_icon = "\uf115"
mapped_locations = [["~", "\uf015"]]

[[blocks.segments]]
type = "python"
style = "plain"
background = "transparent"
foreground = "#FFE873"  # Classic python yellow
template = " \ue235 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "

[blocks.segments.properties]
display_mode = "files"
display_version = true
display_virtual_env = true
home_enabled = true

[[blocks.segments]]
type = "node"
style = "plain"
background = "transparent"
foreground = "#8CCF7E"  # Soft node green
template = " \ue718 {{ if .Error }}{{ .Error }}{{ else }}{{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }}{{ end }} "

[blocks.segments.properties]
fetch_package_manager = true
npm_icon = " <#FF6B6B>\ue5fa</> "  # Warm red for npm
yarn_icon = " <#5CCFE6>\ue6a7</>"   # Cool cyan for yarn

[[blocks.segments]]
type = "rust"
style = "plain"
background = "transparent"
foreground = "#DEA584"  # Warm rust orange
template = " \ue7a8 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "

[[blocks.segments]]
type = "go"
style = "plain"
background = "transparent"
foreground = "#5CCFE6"  # Bright cyan
template = " \ue626 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "

[[blocks.segments]]
type = "java"
style = "plain"
background = "transparent"
foreground = "#E06C75"  # Soft red
template = " \ue738 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "

[[blocks.segments]]
type = "dotnet"
style = "plain"
background = "transparent"
foreground = "#3B7AC9"  # Refined blue
template = " \ue77f {{ if .Unsupported }}\uf071{{ else }}{{ .Full }}{{ end }} "

[[blocks.segments]]
type = "dart"
style = "plain"
background = "transparent"
foreground = "#44B4CC"  # Dart blue
template = " \ue798 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "

[[blocks.segments]]
type = "angular"
style = "plain"
background = "transparent"
foreground = "#E06C75"  # Soft red
template = " \ue753 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "

[[blocks.segments]]
type = "ruby"
style = "plain"
background = "transparent"
foreground = "#D94A7A"  # Ruby red
template = " \ue791 {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "

[[blocks.segments]]
type = "git"
style = "plain"
background = "transparent"
foreground = "#4AF626"  # Matching terminal green
template = "{{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }}"

[blocks.segments.properties]
branch_max_length = 25
fetch_stash_count = true
fetch_status = true
branch_icon = "\uf418 "
branch_identical_icon = "\uf444"
branch_gone_icon = "\ueab8"

# Changed from background templates to foreground for transparent style
foreground_templates = [
  "{{ if or (.Working.Changed) (.Staging.Changed) }}#FFB86C{{ end }}",  # Warm amber for changes
  "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#D8DEE9{{ end }}",
  "{{ if gt .Ahead 0 }}#BD93F9{{ end }}",  # Soft purple for ahead
  "{{ if gt .Behind 0 }}#BD93F9{{ end }}",  # Soft purple for behind
]

[[blocks.segments]]
type = "executiontime"
style = "plain"
background = "transparent"
foreground = "#D8DEE9"  # Soft white
template = " \ueba2 {{ .FormattedMs }} "

[blocks.segments.properties]
style = "austin"
always_enabled = true

[[blocks.segments]]
type = "time"
style = "plain"
background = "transparent"
foreground = "#4AF626"  # Matching terminal green
template = " \uf073 {{ .CurrentDate | date .Format }} "

[blocks.segments.properties]
time_format = "15:04:05"

# Second block for prompt character
[[blocks]]
type = "prompt"
alignment = "left"
newline = true

[[blocks.segments]]
type = "text"
style = "plain"
foreground_templates = [
  "{{if gt .Code 0}}#FF6B6B{{end}}",
  "{{if eq .Code 0}}#4AF626{{end}}"
]
template = "{{ if .Root }}#{{else}}${{end}}"

[transient_prompt]
template = "❯ "
background = "transparent"
foreground_templates = [
  "{{if gt .Code 0}}#FF6B6B{{end}}",
  "{{if eq .Code 0}}#4AF626{{end}}"
]

[secondary_prompt]
template = "❯❯ "
foreground = "#4AF626"
background = "transparent"
